[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
license = "agpl-3.0-or-later"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
vts_parsing = "1.0.2"
